// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_PCC.EntityModels;

[Table("tbl_Technician")]
public class TblTechnician
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string ContactNumber { get; set; }

    public string Email { get; set; }

    public DateTime? Date_Registered { get; set; }

    public string Created_By { get; set; }
}